name: test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.0'
      - name: deps
        run: |
          go get -u golang.org/x/lint/golint
      - name: vet and lint
        run: |
          go vet .
          golint .
      - name: test
        run: go test -v -cover
